#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
noColor='\033[0m'
# for XXX and YYY
projectDir=$(git rev-parse --show-toplevel)
lintProjects=("app" "lintaar")

for project in ${lintProjects[@]}
do
# Android lint check
echo "-----------------Starting run android lint for ${project}-----------------"
projece_issue_file_cmd=`./gradlew ${project}:lint 2>/dev/null | grep  'Ran lint on variant|Wrote HTML report to file:' >> project_issue.txt`
done

cat project_issue.txt

while read line
do
    echo $line
done < project_issue.txt

lineCount=`cat project_issue.txt |wc -l`
if [[ lineCount -ne 0  ]]; then
	echo $lineCount
	exit 1
fi
